export const mockRooms = [
  {
    id: "room_001",
    title: "Frontend System Design",
    language: "JavaScript",
    status: "live", // live | scheduled | ended
    isPrivate: false,
    host: {
      name: "Alice",
      avatar: "/avatars/alice.png",
    },
    scheduledAt: null,
    startedAt: "2025-05-28T10:00:00Z",
    participants: 3,
    maxParticipants: 5,
  },
  {
    id: "room_002",
    title: "ML Case Interview Prep",
    language: "Python",
    status: "scheduled",
    isPrivate: false,
    host: {
      name: "Bob",
      avatar: "/avatars/bob.png",
    },
    scheduledAt: "2025-06-01T15:00:00Z",
    startedAt: null,
    participants: 0,
    maxParticipants: 2,
  },
  {
    id: "room_003",
    title: "Backend with Rust",
    language: "Rust",
    status: "live",
    isPrivate: true,
    host: {
      name: "Clara",
      avatar: "/avatars/clara.png",
    },
    scheduledAt: null,
    startedAt: "2025-05-28T09:30:00Z",
    participants: 2,
    maxParticipants: 2,
  },
  {
    id: "room_004",
    title: "DSA Mock Interview",
    language: "C++",
    status: "scheduled",
    isPrivate: false,
    host: {
      name: "Dan",
      avatar: "/avatars/dan.png",
    },
    scheduledAt: "2025-06-02T13:30:00Z",
    startedAt: null,
    participants: 1,
    maxParticipants: 2,
  },
  {
    id: "room_005",
    title: "AI Ethics Roundtable",
    language: "General",
    status: "ended",
    isPrivate: false,
    host: {
      name: "Eva",
      avatar: "/avatars/eva.png",
    },
    scheduledAt: "2025-05-25T18:00:00Z",
    startedAt: "2025-05-25T18:00:00Z",
    participants: 4,
    maxParticipants: 6,
  },
];
