import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { RootAuthGuard } from "@/components/auth/RootAuthGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootAuthGuard>
          <Navbar />
          {children}
          <Toaster position="top-center" className=" rounded-sm" />
          <Footer />
        </RootAuthGuard>
      </body>
    </html>
  );
}
