"use client";
// import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {hideLayout && <Navbar />}
        <br />
        {children}
        <br />
        {hideLayout && <Footer />}
      </body>
    </html>
  );
}
