import type { Metadata } from "next";
import LeftTools from "./LeftTools";
import RightEditor from "./RightEditor";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full justify-between">
      <ResizablePanelGroup direction="horizontal">
        <ResizablePanel minSize={30} defaultSize={50}>
          <LeftTools />
        </ResizablePanel>
        <ResizableHandle withHandle />
        <ResizablePanel minSize={30} defaultSize={50}>
          <RightEditor />
        </ResizablePanel>
      </ResizablePanelGroup>{" "}
      {children}
    </div>
  );
}
