import type { Metadata } from "next";
import LeftTools from "./LeftTools";
import RightEditor from "./RightEditor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full justify-between">
      <LeftTools />
      {children}
      <RightEditor />
    </div>
  );
}
